# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Build App Teste

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 20
      uses: actions/setup-java@v4
      with:
        java-version: '20'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn package -DskipTests
    - run: ls target
    - run: mv target/*.jar cadastros.jar
      
    - uses:  actions/upload-artifact@v4
      with:
        name: Package
        path: target

    - name: dockerbuild
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: willianovais/ptransportes:latest