# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Build App Teste

on: push

jobs:
  Build Jar:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 20
      uses: actions/setup-java@v4
      with:
        java-version: '20'
        distribution: 'temurin'

    - name: Build Hexburguer Jar
      run: |
      mvn package -DskipTests
      mkdir build
      cp target/*.jar build/cadastros.jar
      
    - name: Gera Artefato
      uses:  actions/upload-artifact@v4
      with:
        name: Package
        path: build

  docker:
    needs: buildapp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.6.1

      - name: Download Artefato
        uses: actions/download-artifact@v4.1.8
        with:
          name: Package
          path: build
      
      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Gera Tag Versao
        run: |
          echo ::set-output name=version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
        id: get_version

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: | 
            willianovais/ptransportes:latest
            willianovais/ptransportes:${{ steps.project.outputs.version }}